## This is an example of a notebook

In [2]:
import numpy as np 

In [2]:
a = np.random.randn(5)

In [3]:
print(a)

[-0.61995998 -1.207169    0.08671838  0.66262787  1.9865137 ]


In [4]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[-0.61995998 -1.207169    0.08671838  0.66262787  1.9865137 ]


In [6]:
print(np.dot(a,a.T))

6.234439821201556


In [3]:
a = np.random.randn(5,1)

print(a)

In [4]:
print(np.dot(a,a.T))

[[ 1.51607049e-01 -4.02606262e-02  8.41065030e-03  1.02108991e-01
  -5.65767216e-01]
 [-4.02606262e-02  1.06915743e-02 -2.23352444e-03 -2.71159681e-02
   1.50244613e-01]
 [ 8.41065030e-03 -2.23352444e-03  4.66594655e-04  5.66466414e-03
  -3.13868666e-02]
 [ 1.02108991e-01 -2.71159681e-02  5.66466414e-03  6.87715119e-02
  -3.81050353e-01]
 [-5.65767216e-01  1.50244613e-01 -3.13868666e-02 -3.81050353e-01
   2.11133022e+00]]


In [15]:
b = np.array([[[1],[2]],[[3],[4]]])
print(b.shape)

(2, 2, 1)


In [14]:
c = np.random.randn(3,3) * np.random.randn(1,3)
print(c.shape)

(3, 3)


In [19]:
a=np.array([[1,1],[1,-1]])
b=np.array([[2],[3]])
c = a+b
print(c.shape)
print(c)

(2, 2)
[[3 3]
 [4 2]]


In [28]:
a = np.random.randn(3,4)
b = np.random.randn(4,1)
print(a)
print('\n\n')
print(b.T)
print('\n\n')
print(a + b.T)

[[-0.18168762  1.07036139  0.53836862  2.12247964]
 [-0.14767673  0.43274843 -0.91540196  0.35301755]
 [ 1.0442723   0.88771822 -0.99766915 -0.0984916 ]]



[[-0.00398616 -1.03716661  0.45635547  1.55013966]]



[[-0.18567378  0.03319478  0.99472409  3.6726193 ]
 [-0.15166289 -0.60441818 -0.45904649  1.90315721]
 [ 1.04028613 -0.14944838 -0.54131368  1.45164806]]


In [29]:
a = np.array([[2,1],[1,3]])
print(np.dot(a,a))

[[ 5  5]
 [ 5 10]]


SyntaxError: invalid syntax (3271798493.py, line 1)