In [28]:
import torch as t
import numpy as np
import time 
device = 'cuda' if t.cuda.is_available() else 'cpu'
device 

'cpu'

In [3]:
## Basic tensor creations

randTensor = t.randint(-100,100,(6,))
randTensor

tensor([ 98,  32,  48,  14,  89, -22])

In [9]:
t.tensor([[1,2,3],[4.2,5.1,6.1])

tensor([[1.0000, 2.0000, 3.0000],
        [4.2000, 5.1000, 6.1000]])

In [10]:
t.zeros(5,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [37]:
%%time
t.ones(2,4)

CPU times: user 691 µs, sys: 1.38 ms, total: 2.07 ms
Wall time: 2.51 ms


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
t.empty(1,2)

tensor([[0., 0.]])

In [17]:
t.arange(0,5)

tensor([0, 1, 2, 3, 4])

In [19]:
t.linspace(3,19,steps=5)

tensor([ 3.,  7., 11., 15., 19.])

In [22]:
t.logspace(start=-10,end=10,steps=5)

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [23]:
t.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [25]:
empty = t.empty(2,3, dtype=t.int64)
empty_like = t.empty_like(empty)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [94]:
## Timing matrix operations

### Init 
start = time.time()
zeros = t.zeros(1000,1000)
end = time.time()
#print(f'Init 1000*1000 : {(end-start):.8f}')


### Multiply 

start = time.time()
t_ones_a = t.rand(1000,1000)
t_ones_b = t.rand(1000,1000)
result = (t_ones_a @ t_ones_b)
end = time.time()
print(f' Torch Multiply 1000*1000 : {(end-start):.8f}')

start = time.time()
np_ones_a = t.rand(1000,1000)
np_ones_b = t.rand(1000,1000)
result = np.multiply(np_ones_a,np_ones_b)
end = time.time()
print(f' Np Multiply 1000*1000 : {(end-start):.8f}')


start = time.time()
np_ones_a = t.rand(1000,1000)
np_ones_b = t.rand(1000,1000)
result = t.matmul(np_ones_a,np_ones_b)
end = time.time()
print(f' Torch MatMul 1000*1000 : {(end-start):.8f}')


 Torch Multiply 1000*1000 : 0.01877832
 Np Multiply 1000*1000 : 0.00907326
 Torch MatMul 1000*1000 : 0.00907493


In [93]:
# Define a probablity tensor
tensor = t.tensor([0.1,0.9])

# Get 10 samples from probablity set
samples = t.multinomial(tensor, num_samples=10,replacement=True)
print(f'Probablities {samples}')

Probablities tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [48]:
# Tensor Concat
out = t.cat((tensor,t.tensor([5])),dim=0)
print(f'Concat {out}')

Concat tensor([0.1000, 0.9000, 5.0000])


In [49]:
# Tensor Tril - Triangle Lower
## Based on history of knowledge, predict what's next? 
trill = t.tril(t.ones(5,5))
print(f'Tril {trill}')


# Tensor Tril - Triangle Upper
## Based on history of knowledge, predict what's next? 
triu = t.triu(t.ones(5,5))
print(f'Triu {triu}')

Tril tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])
Triu tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])


In [52]:
# Masked Fill

out = t.zeros(5,5).masked_fill(t.tril(t.ones(5,5))==0,float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [54]:
# e ^ values in matrix

t.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [59]:
# Transposing
input = t.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [62]:
# Stack tensors along a dimension 

tensor1 = t.tensor([1,2,3])
tensor2 = t.tensor([4,5,6])
tensor3 = t.tensor([7,8,9])

stacked_tensor = t.stack([tensor1,tensor2,tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [66]:
# Torch Neural Network Module

import torch.nn as nn

sample = t.tensor([1.,2.,3.])
linear = nn.Linear(3,3,bias=False)
print(linear(sample))

tensor([-0.6331,  0.9492,  0.1030], grad_fn=<SqueezeBackward4>)


In [81]:
# Softmax Function 
import torch.nn.functional as F

tensor5 = t.tensor([1.0,2.0,3.0])
softmax_out = F.softmax(tensor5, dim=0)
softmax_out

tensor([0.0900, 0.2447, 0.6652])

In [85]:
# Embeddings


# Create an embedding layer.
# This layer will convert word indices into dense vectors of a fixed size.
# Here, we define the following:
# - num_embeddings=1000: Our vocabulary size is 1000. This means we have 1000 unique words.
# - embedding_dim=300: Each word will be represented by a 300-dimensional vector.
embedding = nn.Embedding(num_embeddings=1000, embedding_dim=300)


# Create an example input. 
# This is a tensor containing indices of words. These indices are just numbers that 
# represent words in our vocabulary. For example, 1 might represent "cat", 56 might 
# represent "dog", and so on. The dtype=torch.long specifies that the numbers are integers.
input_indices = t.tensor([1, 56, 700], dtype=t.long)


# Use the embedding layer to get the dense vector representations (embeddings) of our words.
# The 'embedding' layer looks up the vector for each word index in our input_indices.
# So for each number in input_indices, the layer returns a 300-dimensional vector.
embeddings = embedding(input_indices)

# Print out the embeddings to see what they look like.
print(embeddings.shape)


torch.Size([3, 300])


In [89]:
tensor1 = t.tensor([[1,1],[1,1]])
tensor2 = t.tensor([[2,2],[2,2]])
print((tensor1 @ tensor2))

tensor([[4, 4],
        [4, 4]])
