In [28]:
import torch as t
import numpy as np
import time 
device = 'cuda' if t.cuda.is_available() else 'cpu'
device 

'cpu'

In [3]:
## Basic tensor creations

randTensor = t.randint(-100,100,(6,))
randTensor

tensor([ 98,  32,  48,  14,  89, -22])

In [9]:
t.tensor([[1,2,3],[4.2,5.1,6.1])

tensor([[1.0000, 2.0000, 3.0000],
        [4.2000, 5.1000, 6.1000]])

In [10]:
t.zeros(5,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [11]:
t.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
t.empty(1,2)

tensor([[0., 0.]])

In [17]:
t.arange(0,5)

tensor([0, 1, 2, 3, 4])

In [19]:
t.linspace(3,19,steps=5)

tensor([ 3.,  7., 11., 15., 19.])

In [22]:
t.logspace(start=-10,end=10,steps=5)

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [23]:
t.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [25]:
empty = t.empty(2,3, dtype=t.int64)
empty_like = t.empty_like(empty)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [35]:
## Timing matrix operations

### Init 
start = time.time()
zeros = t.zeros(1000,1000)
end = time.time()
print(f'Init 1000*1000 : {(end-start):.8f}')


### Multiply 

start = time.time()
t_ones_a = t.rand(1000,1000)
t_ones_b = t.rand(1000,1000)
result = (t_ones_a @ t_ones_b)
end = time.time()
print(f' Torch Multiply 1000*1000 : {(end-start):.8f}')

start = time.time()
np_ones_a = t.rand(1000,1000)
np_ones_b = t.rand(1000,1000)
result = np.multiply(np_ones_a,np_ones_b)
end = time.time()
print(f' Np Multiply 1000*1000 : {(end-start):.8f}')





Init 1000*1000 : 0.00091696
 Torch Multiply 1000*1000 : 0.02043819
 Np Multiply 1000*1000 : 0.00812888
